In [1]:
# import statements
import numpy as np
import random as rand

#### Please refer to module 1 of DataWranglingInPython - DataWranglingWithNumpy for Tasks 1-6 
#### Task 1
##### Create an array of 25 numbers between 1 and 100 (including 100) and save to `arr1` variable.
##### Print the type and data type of `arr1`.


#### Result:


In [2]:
# creating a list name arr1
arr1 = []
for i in range(0,25):
    n = rand.randint(1,100)
    arr1.append(n)
    
# converting the list (arr1) into an array and then printing the type and values within the array    
arr1 = np.array(arr1)
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[50 33 60 80 57 26 69 37 57 50 42 93 51 59 80  3 95 82  5 59 67  9 97 80
 77]


#### Task 2
##### Create an array of 20 numbers from 50 to 70 (excluding 70).
##### Use the `arange` function and assign the output to `arr2` variable.


#### Result:


In [3]:
# creating nother array (arr2) using np.arange() function
arr2 = np.arange(50,70)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


#### Task 3
##### Create an array of 10 numbers between 0 and 20 (including 20) and assign to `arr3` variable.
##### Use `linspace` function.
##### Find the max, min, and sum of the array.


#### Result:


In [4]:
# Creating another array (arr3) using np.linspace() function
# Then printing the max, min, and sum functions from python's built-in functionality
arr3 = np.linspace(1, 20, 10)
print('min:',min(arr3))

print('max:',max(arr3))

print('sum:',sum(arr3))

min: 1.0
max: 20.0
sum: 105.0


#### Task 4
##### Create two arrays of size 4 with the numbers 4, 5, 6, 4 in `array1` and 7, 2, 12, 16 in `array2`.
##### Find the `sum`,  `product`, `difference`, and `quotient` of `array1` and `array2`. Save the results as `array_sum`, `product`, `difference`, and `quotient` variables, respectively.
##### Print the results.


#### Result:


In [5]:
# creating two arrays from the prompt as array1 and array2
array1 = np.array([4,5,6,4])
array2 = np.array([7,2,12,16])

# doing mathematical operations on the arrays
array_sum = sum(array1,array2)
product = array1 * (array2)
difference = array1 - (array2)
quotient = array1 / (array2)

In [6]:
# printing the values of the mathematical operations
print('sum:', array_sum)
print('product:', product)
print('difference:', difference)
print('quotient:', quotient)

sum: [26 21 31 35]
product: [28 10 72 64]
difference: [ -3   3  -6 -12]
quotient: [0.57142857 2.5        0.5        0.25      ]



#### Task 5
##### Compute the absolute value of each entry in the following array: `[5, -8, -66, 4]`.
##### Assign the operation to `abs_values` variable. Print the result.
##### Print the length of the `abs_values` array.
##### Print the 3rd element of `abs_values`.


#### Result:


In [7]:
# Using the np.abs() absolute number function to get rid of the negative values
abs_values = (np.abs([5, -8, -66, 4]))
print(abs_values)
print(len(abs_values))
print(abs_values[2])

[ 5  8 66  4]
4
66


#### Task 6
##### Print all numbers greater than 25 in `abs_values` array.


#### Result:


In [8]:
# filtering the abs_values array for values that greater than 25
print(abs_values[abs_values > 25])

[66]


#### Please refer to module 2 of DataWranglingInPython - DataWranglingWithNumpy for Tasks 7-8
#### Task 7
##### Create the following matrix with 3 rows and assign to variable `mat1`:


- [4, 5, 6]
- [8, 3, 2]
- [6, 7, 3]



##### Find the shape of the matrix.


#### Result:


In [9]:
# Creating a matrix of the 3 arrays listed above and then printing the shape of the matrix
mat1 = np.array([[4, 5, 6],[8, 3, 2],[6, 7, 3]])
print(mat1.shape)

(3, 3)


#### Task 8
##### Find the value in the 2nd row and 3rd column of `mat1`.
##### Print the 2nd and 3rd rows.
##### Print the 1st column and rows up to the 2nd row.
##### Print all columns starting with column 2.


#### Result:


In [10]:
# Matrix indexing
print(mat1[1,2])
print(mat1[1])
print(mat1[2])
print(mat1[:,1:])

2
[8 3 2]
[6 7 3]
[[5 6]
 [3 2]
 [7 3]]


#### Bonus Task 1


##### Filter and print the elements greater than 5 in `mat1`.
##### Use a Boolean mask to filter all elements <= 5 and set them to 0.
##### Print the resulting matrix.


#### Result:


In [12]:
# Filtering the matrix for values greater than 5 and then setting all values that are 5 and smaller to 0
print(mat1[mat1 > 5])

mat1[mat1 <=5] = 0

print(mat1)

[6 8 6 7]
[[0 0 6]
 [8 0 0]
 [6 7 0]]


#### Bonus Task 2
##### Use the `linspace` function to create a NumPy array of 16 numbers between 10 and 25 (inclusive) called `arr4`.
##### Reshape the array to a matrix of shape (4,4) and print it.
##### Reshape the array to a matrix with 8 rows and let Python infer the number of columns.


#### Result:


In [13]:
# Creating an array (arr4) that contains 16 values between 10 and 25, evenly spaced
arr4 = np.linspace(10,25,16)

In [14]:
arr4

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25.])

In [15]:
# reshaping the array into a 4x4 matrix
arr4.reshape([4,4])

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.],
       [22., 23., 24., 25.]])

In [17]:
# reshaping the matrix into an 8x2 matrix
arr4.reshape([8,-1])

array([[10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.],
       [24., 25.]])